swagger: "2.0"
info:
  description: "I haven't thought of any description yet :("
  version: "1.0.0"
  title: "University Model"
host: "localhost:8083"
basePath: "/api"
tags:
- name: "student"
  description: "Everything about students"
- name: "employee"
  description: "Everything about employees"
- name: "school"
  description: "Everything about schools"
- name: "course"
  description: "Everything about schools"
- name: "department"
  description: "Everything about departments"  
schemes:
- "http"
paths:
  /students:
    post:
      tags:
      - "student"
      summary: "Add a new student"
      description: ""
      operationId: "addStudent"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Student object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/StudentFilter"
      responses:
        "400":
          description: "Bad request"
        "201": 
          description: "Successfull operation"
          schema:
             $ref: '#/definitions/Human'
    get:
      tags: 
        - "student"
      summary: "Get a list of all students or one student"
      description: ""
      operationId: "getStudent"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/StudentFilter"
      responses:
        "404":
          description: "Not Found"
        "200": 
          description: "Successfull operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Human"
    delete:
      tags: 
        - "student"
      summary: ""
      description: ""
      operationId: "delStudent"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/StudentFilter"
      responses:
        "404":
          description: "Not Found"
        "204": 
          description: "Successfull operation"
    patch:
      tags: 
        - "student"
      summary: ""
      description: ""
      operationId: "updateStudent"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/StudentFilter"
      responses:
        "400":
          description: "Bad request"
        "204": 
          description: "Successfull operation"
              
  /student/grades:
    get:
      tags: 
      - "student"
      summary: "Get student grades"
      description: ""
      operationId: "getGrades"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/StudentFilter"
      responses:
        "404":
          description: "Not Found"
        "200": 
          description: "Successfull operation"
          
  /courses:
    get:
      tags:
        - "course"
      summary: "******"
      description: ""
      operationId: "getCourses"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/CourseFilter"
      responses:
        "404":
          description: "Not Found"
        "200": 
          description: "Successfull operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Course"
    post:
      tags:
        - "course"
      summary: "******"
      description: ""
      operationId: "addCourse"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/Course"
      responses:
        "400":
          description: "Bad Request"
        "201": 
          description: "Successfull operation"
          schema:
            $ref: "#/definitions/Course"
    delete:
      tags:
        - "course"
      summary: "******"
      description: ""
      operationId: "delCourse"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/CourseFilter"
      responses:
        "400":
          description: "Bad request"
        "204": 
          description: "Successfull operation"
    patch:
      tags: 
        - "course"
      summary: ""
      description: ""
      operationId: "updateCourse"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/CourseFilter"
      responses:
        "400":
          description: "Bad request"
        "204": 
          description: "Successfull operation"
    
  /schools:
    get:
      tags:
        - "school"
      summary: "******"
      description: ""
      operationId: "getSchools"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/SchoolFilter"
      responses:
        "404":
          description: "Not Found"
        "200": 
          description: "Successfull operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/School"
    post:
      tags:
        - "school"
      summary: "******"
      description: ""
      operationId: "addSchool"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/School"
      responses:
        "400":
          description: "Bad request"
        "201": 
          description: "Successfull operation"
          schema:
            $ref: '#/definitions/School'
    delete:
      tags:
        - "school"
      summary: "******"
      description: ""
      operationId: "delSchool"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/SchoolFilter"
      responses:
        "400":
          description: "Bad request"
        "204": 
          description: "Successfull operation"
    patch:
      tags: 
        - "school"
      summary: ""
      description: ""
      operationId: "updateSchool"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/SchoolFilter"
      responses:
        "400":
          description: "Bad request"
        "204": 
          description: "Successfull operation"
            
  /school/employees:
    get:
      tags:
        - "employee"
      summary: "******"
      description: ""
      operationId: "getEmployees"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/EmployeeFilter"
      responses:
        "404":
          description: "Not Found"
        "200": 
          description: "Successfull operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Human"
    post:
      tags:
        - "employee"
      summary: "******"
      description: ""
      operationId: "addEmployee"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/Human"
      responses:
        "400":
          description: "Bad request"
        "201": 
          description: "Successfull operation"
          schema:
            $ref: "#/definitions/Human"
            
    delete:
      tags:
        - "employee"
      summary: "******"
      description: ""
      operationId: "delEmployee"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/EmployeeFilter"
      responses:
        "400":
          description: "Bad request"
        "204": 
          description: "Successfull operation"
    patch:
      tags: 
        - "employee"
      summary: ""
      description: ""
      operationId: "updateEmployee"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/EmployeeFilter"
      responses:
        "400":
          description: "Bad request"
        "204": 
          description: "Successfull operation"
      
  /departments:
    get:
      tags:
        - "department"
      summary: "******"
      description: ""
      operationId: "getDepartments"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/DepartmentFilter"
      responses:
        "404":
          description: "Not Found"
        "200": 
          description: "Successfull operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Department"
    post:
      tags:
        - "department"
      summary: "******"
      description: ""
      operationId: "addDepartment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/Department"
      responses:
        "404":
          description: "Not Found"
        "200": 
          description: "Successfull operation"
          schema:
            $ref: "#/definitions/Department"
    delete:
      tags:
        - "department"
      summary: "******"
      description: ""
      operationId: "delDepartment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/DepartmentFilter"
      responses:
        "404":
          description: "Not Found"
        "204": 
          description: "Successfull operation"
    patch:
      tags: 
        - "department"
      summary: ""
      description: ""
      operationId: "updateDepartment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/DepartmentFilter"
      responses:
        "400":
          description: "Bad request"
        "204": 
          description: "Successfull operation"
            
  /department/groups:
    get:
      tags:
        - "department"
      summary: "******"
      description: ""
      operationId: "getGroups"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/GroupFilter"
      responses:
        "404":
          description: "Not Found"
        "200": 
          description: "Successfull operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Group"
    post:
      tags:
        - "department"
      summary: "******"
      description: ""
      operationId: "addGroup"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/Group"
      responses:
        "400":
          description: "Bad requset"
        "201": 
          description: "Successfull operation"
          schema:
            $ref: "#/definitions/Group"
    delete:
      tags:
        - "department"
      summary: "******"
      description: ""
      operationId: "delGroup"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "******"
        required: true
        schema:
          $ref: "#/definitions/GroupFilter"
      responses:
        "400":
          description: "Bad requset"
        "204": 
          description: "Successfull operation"
    patch:
      tags: 
        - "department"
      summary: ""
      description: ""
      operationId: "updateGroup"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/GroupFilter"
      responses:
        "400":
          description: "Bad request"
        "204": 
          description: "Successfull operation"

definitions:
  Human:
    type: "object"
    required:
    - "fullName"
    - "birthDate"
    - "role"
    properties:
      fullName:
        type: "string"
        example: "Cressida Wells"
      birthDate:
        type: "string"
        format: "date"
        example: "1999-07-15"
      department:
        type: "string"
      school:
        type: "string"
      role:
        type: "string"
        pattern: '(STUDENT|PROFESSOR|POSTGRADUATE)'
        example: "[Must match this pattern: (STUDENT|PROFESSOR|POSTGRADUATE)]"
        
  Course:
    type: "object"
    required:
    - "courseName"
    - "duration"
    - "courseType"
    - "department"
    properties:
      courseName:
        type: "string"
      duration:
        type: "integer"
        format: "int64"
      courseType:
        type: "string"
      department:
        type: "string"
        
  School:
    type: "object"
    required:
    - "schoolName"
    properties:
      schoolName:
        type: "string"
      departments:
        type: "array"
        items:
          $ref: "#/definitions/Department"
        
  Group:
    type: "object"
    required:
    - "groupName"
    properties:
      groupName:
        type: "string"
      schoolName:
        type: "string"
      dptName:
        type: "string"
      students:
        type: "array"
        items:
          $ref: "#/definitions/Human"
        
  Department:
    type: "object"
    required:
    - "name"
    - "school"
    properties:
      dptName:
        type: "string"
      school:
        type: "string"
        
  DepartmentFilter:
    type: "object"
    properties:
      dptName:
        type: "string"
      school:
        type: "string"
      updates:
        $ref: "#/definitions/Updates"
    
  SchoolFilter:
    type: "object"
    properties:
      schoolName:
        type: "string"
      updates:
        $ref: "#/definitions/Updates"
        
  GroupFilter:
    type: "object"
    properties:
      groupName:
        type: "string"
      updates:
        $ref: "#/definitions/Updates"
        
  StudentFilter:
    type: "object"
    properties:
      studentFullName:
        type: "object"
        properties:
          firstName:
            type: "string"
          lastName:
            type: "string"
      avgGradeBounds:
        type: "object"
        properties:
          upperBound:
            type: "number"
          lowerBound:
            type: "number"
      dateOfBirth:
        type: "object"
        properties:
          upperBound:
            type: "string"
            format: "date"
          lowerBound:
            type: "string"
            format: "date"
      updates:
        $ref: "#/definitions/Updates"
            
  EmployeeFilter:
    type: "object"
    properties:
      employeeFullName:
        type: "string"
      schoolName:
        type: "string"
      dptName:
        type: "string"
      role:
        type: "string"
        pattern: '(PROFESSOR|POSTGRADUATE)'
      dateOfBirth:
        type: "object"
        properties:
          upperBound:
            type: "string"
            format: "date"
          lowerBound:
            type: "string"
            format: "date"
      updates:
        $ref: "#/definitions/Updates"
            
  Updates:
    type: "object"
    properties:
      schoolName:
        type: "string"
      dptName:
        type: "string"
      groupName:
        type: "string"
      courseName:
        type: "string"
      courseType:
        type: "string"
        pattern: '(SOCIAL|MATHEMATICAL)'
      role:
        type: "string"
        pattern: '(PROFESSOR|POSTGRADUATE)'
      firstName:
        type: "string"
      lastName:
        type: "string"
      dateOfBirth:
        type: "string"
        format: "date"
      duration:
        type: "integer"
        format: "int64"
            
  Filter:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 31415926 
        
  CourseFilter:
    type: "object"
    properties:
      courseType:
        type: "string"
        pattern: '(SOCIAL|MATHEMATICAL)'
      duration:
        type: "integer"
        format: "int64"
      department:
        type: "string"
      updates:
        $ref: "#/definitions/Updates"
    
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"